name: "dummy_LM"

type: "dummy"
model_template: "dummy_model"

mixins: 

tokenizer_config:
  pretrained_model_name_or_path: ""

tokenizer:  
  pretrained_model_name_or_path: ""


generation_config: 
  return_dict_in_generate: true
  output_scores: false
  do_sample: false

encode_config:

decode_config:

stream_config: